### ISSUE TITLE
Add new shortcuts for block creations

### ISSUE THREAD

**Issue by FabienRoger** [Bycelium/PyFlow#109]
In a Jupyter notebook, adding new blocks is easy. Just press "Shift+Enter" and it adds a new block after executing the current one.
In OCB, for now, you have to right-click, new block, and link it with the previous one, which is cumbersome.

The new shortcuts which could be added:
- Shift+ Arrow to add a new block linked to the current one in the direction of the arrow and launch the execution of the current cell
- Shift+ Enter to add a new block linked to the current one to the right and launch the execution of the current cell
- Control + Enter to execute the current cell
- Something to insert a cell between two others (this is *really* slow with the current system)

**Comment by vanyle** [comment]
This is related to #108 
The will probably be fixed in the same pull request.

**Comment by AlexandreSajus** [comment]
A button to add a linked code block under another one has been added in #266

**Comment by MathisFederico** [comment]
Alt + Shift + Down should trigger the AddBlockButton

I think we could close this issue once this is done as block insertion is already mentioned in #228 and  #230 

In fact, Alt + Shift + Down could also trigger insertion if there is an existing linked block once it is implemented.

**Comment by FabienRoger** [comment]
Here is the new behavior with (Alt+)Shift + Arrow:
![image](https://user-images.githubusercontent.com/15524303/155188083-2638296c-413b-4292-a19b-21a706f79c28.png)
