### ISSUE TITLE
Ipynb conversion does not work

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#128]
Currently loading an ipynb file crashes because in:
https://github.com/Bycelium/PyFlow/blob/master/opencodeblocks/scene/from_ipynb_conversion.py#L64
line is undefined

Also,
Run_right does not work in an ipynb converted notebook because it finds edges with None as destination_socket

**Comment by FabienRoger** [comment]
The current pull request doesn't solve the second part ("Run_right does not work in an ipynb converted notebook because it finds edges with None as destination_socket")
