### ISSUE TITLE
Left to Right Structure is incompatible with long notebooks

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#149]
Loading a notebook with a huge amount of blocks creates a really hard to navigate and read long line of blocks:
![image](https://user-images.githubusercontent.com/62465003/149357215-264929bb-342c-4d8e-9794-15430a0529fc.png)

A top to bottom structure might work better:
![image](https://user-images.githubusercontent.com/62465003/149357286-32f797dc-909d-422a-9120-b04cbf74b584.png)

**Comment by MathisFederico** [comment]
This will be solved by #186

**Comment by MathisFederico** [comment]
Solved by #186
