### ISSUE TITLE
Refactor Markdown block

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#153]
A alpha tester said that he did not know how to edit a markdown block

I had to explain that what he was seeing was the output of the block and not its editor and he did not see the divider:
![image](https://user-images.githubusercontent.com/62465003/149361558-8853dbb6-cdb6-439d-9c5c-8b5d8906bd48.png)

Using Ctrl+Enter or a button to enter editor mode could solve this

**Comment by MathisFederico** [comment]
The Markdown block should not have a similar output panel as codeblock.
Markdown blocks should be edited by double-clicking on it and then be transformed as md output when unfocused like in many .md editors (obsidian, colab, ...)

**Comment by FabienRoger** [comment]
Fixed by #269
