### ISSUE TITLE
Converting notebooks can hit the window width limit

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#168]
Loading a huge notebook creates such a long line of blocks that it hits the width limit of the window:
![image](https://user-images.githubusercontent.com/62465003/149370303-bde7507f-d236-4458-97b1-2f4ff108eea4.png)

Also scrolling inside this block is not possible

**Comment by AlexandreSajus** [comment]
The example notebook is Fast_NST.ipynb in the alpha_testing channel of our discord

**Comment by MathisFederico** [comment]
Line wrapping would solve this
