### ISSUE TITLE
Remove ipynb conversion for now?

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#188]
In alpha testing, every tester that started using Pyflow in a converted notebook (that was often extremely long) was instantly confused by the lack of ergonomy and the point of Pyflow.

Visual flow has no point in a fully linear graph of codeblocks and the user has no incentive to use it. Furthermore, the amount of freedom the user has on a 2D plane (resizing, moving, linking blocks) makes Pyflow a really tedious notebook editor.

Ipynb should maybe be removed for now or at least should have a restricted access or a warning prompt, so that new users don't start their experience on a converted notebook

**Comment by FabienRoger** [comment]
I see! I think I agree.

Ultimately, I believe some improvements could make it usable even for new users, but we are far from it right now.

The improvements I am thinking about are improvements that read the code to understand which block need which block, to create a coherent ipyg graph (by linking, moving and merging cells automatically) without too much tinkering.

**Comment by MathisFederico** [comment]
I think we should keep it, users would just need a tutorial before, but the feature is too important to be removed
