### ISSUE TITLE
Visual flow can be unintuitive

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#190]
Running run_right on Block S gives that inintuitive output
![image](https://user-images.githubusercontent.com/62465003/149425004-5bd7712c-911e-4a58-9056-09f39c88f23f.png)

**Comment by MathisFederico** [comment]
> Running run_right on Block S gives that inintuitive output
> ![image](https://user-images.githubusercontent.com/62465003/149425004-5bd7712c-911e-4a58-9056-09f39c88f23f.png)
> 

Oh that's due to fonction usage, maybe function should be avoided as you can reuse a block, but then we would need some kind of blocks linking ...
