### ISSUE TITLE
Copying a block in an editor will paste its JSON

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#198]
Copying a block and pasting it into a text editor will paste its JSON contents:
![image](https://user-images.githubusercontent.com/62465003/149428002-c726577e-5cb6-4ab8-8131-2ba68a5ddbce.png)

Clipboard for blocks and for text should be separated

**Comment by FabienRoger** [comment]
The issue is much worse the other way around.
For the moment, pasting *not* inside the editor tries to convert the data to json, and if successful, go on to serialize it.
This means that pasting "{}" inside pyflow (not inside an editor) makes the program crash.
