### ISSUE TITLE
Some converted notebooks have abnormally long code blocks

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#213]
Loading the trick-and-tips-testing.ipynb notebook (alpha-testing channel on Discord) creates abnormally vertically long codeblocks
![image](https://user-images.githubusercontent.com/62465003/149431033-89b66f67-b4a8-459e-9962-6bc7b103de92.png)

**Comment by FabienRoger** [comment]
Weird. I assumed all ipynb notebooks would have the same format, but they don't. Some are lists of lines, some are just one big string. I will fix that!
