### ISSUE TITLE
python -m pyflow PATH does not work anymore

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#234]
Trying to launch Pyflow through an ipyg file raises an error currently. It should open Pyflow with the ipyg file loaded but does not work anymore:

```
(venv) PS C:\Users\asaju\Desktop\Bycelium\PyFlow> python -m pyflow examples\usecases\day-night-classification\day-night-classification.ipyg
usage: __main__.py [-h] [-p PATH]
                   [-v {CRITICAL,FATAL,ERROR,WARN,WARNING,INFO,DEBUG,NOTSET}]
__main__.py: error: unrecognized arguments: examples\usecases\day-night-classification\day-night-classification.ipyg
```

**Comment by MathisFederico** [comment]
That's just because you need the flag -p before the path, as mentioned by the CLI helper:
![image](https://user-images.githubusercontent.com/60117466/151714060-d245be9e-b90f-476a-9346-b026dde76414.png)

Use --help to display CLI help
```bash
python -m pyflow --help
```
