### ISSUE TITLE
Relation to Wonderworks PyFlow?

### ISSUE THREAD

**Issue by asmaier** [Bycelium/PyFlow#238]
Hello,

this seems to be a cool project. 
But I  got confused when I stumbled upon https://pyflow.readthedocs.io/en/latest/ 
and it pointed to a different PyFlow project. 
How is this project here related to https://github.com/wonderworks-software/PyFlow  ?
Is it a fork? Is it something new?

**Comment by AlexandreSajus** [comment]
I understand the confusion, there are a lot of projects called Pyflow.

We first created our project with the name OpenCodeBlocks but we then found PyFlow as a simpler alternative. We then stumbled upon the project from wonderworks-software. We contacted the devs that told us that their project was abandoned and that it was okay for us to use the name Pyflow.

Our Pyflow is something new that is completely unrelated to Wonderworks' Pyflow.
