### ISSUE TITLE
Selecting a block to move it should not move other blocks

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#241]
If I'm in this situation (left block selected):
![image](https://user-images.githubusercontent.com/62465003/151994502-5e6a09e1-54a8-41f2-8411-7ce4477da609.png)

If I try to move the right block, I expect Pyflow to deselect the left block and only move the right block.

Instead, Pyflow selects both and moves them both:
![image](https://user-images.githubusercontent.com/62465003/151994713-dc5694ef-6a6b-44ba-ae05-34a5c9615873.png)

**Comment by MathisFederico** [comment]
This would be fixed by commit 29362feb96f384fdb9fca3b7f4cce770cc9c102e in #118
I should have done a separate branch to fix this my bad
