### ISSUE TITLE
Putting a block out of focus loses the undo history of a block

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#27]
Currently, when a code block goes out of focus, it loses its undo history which means that pressing Ctrl+Z to undo its code does nothing. Ideally, the undo history should be saved per block. The user should be able to undo on a newly focused block.

**Comment by FabienRoger** [comment]
I don't see a way to get the undo history to save it. QsciScintilla fundamental functions seem to work only with "Send", not with "Get"... It might be needed to override the undo function. I will try that if you have no other idea.

**Comment by MathisFederico** [comment]
> I don't see a way to get the undo history to save it. QsciScintilla fundamental functions seem to work only with "Send", not with "Get"... It might be needed to override the undo function. I will try that if you have no other idea.

Yeah that's expected, we will need to overide their undo and to add a consistant buffer.
