### ISSUE TITLE
Run right does not work: it executes itself multiple times

### ISSUE THREAD

**Issue by FabienRoger** [Bycelium/PyFlow#277]
Steps to reproduce:
Take the flow_test asset and add "counter += 1" in Cell 5 in the middle.
Initialize the counter elsewhere.
Run right the cell with the "counter += 1"
Print what is in the counter elsewhere. It contains 4.

![image](https://user-images.githubusercontent.com/15524303/154588013-20f8d2d4-e99a-4f45-ba81-4353a564f213.png)

**Comment by MathisFederico** [comment]
Yup, this clearly need a fix !

**Comment by FabienRoger** [comment]
Fixed directly in #276
