### ISSUE TITLE
🪲 Ctrl+Z crashes the application

### ISSUE THREAD

**Issue by MathisFederico** [Bycelium/PyFlow#288]
On the mnist example:

```bash
    python -m pyflow -v DEBUG -p .\examples\mnist.ipyg
```

When suppressing this block:
![image](https://user-images.githubusercontent.com/60117466/154852012-633d8226-d619-40d2-a52f-ec0504dd0593.png)

![image](https://user-images.githubusercontent.com/60117466/154851985-9b8ecedc-c8a9-4201-8fcb-add82c02913d.png)

Pressing Ctrl+Z crashed the application.

This is probably due to #281.
Could you take a look at it @FabienRoger ?

**Comment by FabienRoger** [comment]
I wasn't able to reproduce the crash, not in the version before #281, nor after, but I fixed two things:
- the leftover edge
- that pressing Ctrl+z just after loading a scene erases everything in the scene
I hope this fixes the crash on your side.
