### ISSUE TITLE
Python Blockly

### ISSUE THREAD

**Issue by runtimevic** [Bycelium/PyFlow#306]
Hi,
Do you know if it exists for Python but instead of codeblocks with blockly google?
thanks you.

**Comment by MathisFederico** [comment]
No idea sorry

**Comment by edgeofinnerspace** [comment]
[BlockPy](https://blockpy.cis.udel.edu/blockpy)
Alternate Host but same App
[BlockPy](https://think.cs.vt.edu/blockpy/)

**Comment by MathisFederico** [comment]
Not really the same app but sure
