### ISSUE TITLE
Kernel CWD is incorrect

### ISSUE THREAD

**Issue by vanyle** [Bycelium/PyFlow#94]
When starting the python kernel, the current working directory should be set relative to the path of the file loaded, not relative to the opencodeblocks program.

This means that when doing:
```python
print(open("data.txt").read())
```
`data.txt` should be located next to the `.ipyg` file, not next to the `opencodeblocks` folder.

**Comment by AlexandreSajus** [comment]
We're not sure wether it is better to have CWD at the location of the .ipyg file or where the package is called from. Let's leave this issue alone for now.
